# Generated by Django 3.2.7 on 2021-09-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
