# Generated by Django 3.2.7 on 2021-09-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210906_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='value',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_phone',
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
    ]
