# Generated by Django 3.2.7 on 2021-09-06 19:18

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210906_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_photo',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='contacts/files/'),
        ),
    ]
