{"rating": "1", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/23.png", "name": "Динамо Киев", "games": "6", "wins": "5", "draws": "1", "losses": "0", "goals_in": "20", "goals_out": "2", "difference": "18", "scores": "16"}
{"rating": "2", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/24.png", "name": "Шахтер", "games": "6", "wins": "4", "draws": "1", "losses": "1", "goals_in": "12", "goals_out": "4", "difference": "8", "scores": "13"}
{"rating": "3", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/1303.png", "name": "Днепр-1", "games": "6", "wins": "4", "draws": "1", "losses": "1", "goals_in": "12", "goals_out": "6", "difference": "6", "scores": "13"}
{"rating": "4", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/290.png", "name": "Десна", "games": "6", "wins": "4", "draws": "0", "losses": "2", "goals_in": "9", "goals_out": "10", "difference": "-1", "scores": "12"}
{"rating": "5", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/78.png", "name": "Ворскла", "games": "6", "wins": "3", "draws": "2", "losses": "1", "goals_in": "11", "goals_out": "5", "difference": "6", "scores": "11"}
{"rating": "6", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/406.png", "name": "Александрия", "games": "6", "wins": "3", "draws": "2", "losses": "1", "goals_in": "7", "goals_out": "5", "difference": "2", "scores": "11"}
{"rating": "7", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/219.png", "name": "Заря", "games": "6", "wins": "3", "draws": "1", "losses": "2", "goals_in": "12", "goals_out": "8", "difference": "4", "scores": "10"}
{"rating": "8", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/533.png", "name": "Верес", "games": "6", "wins": "2", "draws": "2", "losses": "2", "goals_in": "7", "goals_out": "7", "difference": "0", "scores": "8"}
{"rating": "9", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/1209.png", "name": "Ингулец", "games": "6", "wins": "2", "draws": "1", "losses": "3", "goals_in": "8", "goals_out": "11", "difference": "-3", "scores": "7"}
{"rating": "10", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/1302.png", "name": "Рух", "games": "6", "wins": "2", "draws": "1", "losses": "3", "goals_in": "5", "goals_out": "8", "difference": "-3", "scores": "7"}
{"rating": "11", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/1312.png", "name": "Металлист 1925", "games": "6", "wins": "2", "draws": "0", "losses": "4", "goals_in": "6", "goals_out": "10", "difference": "-4", "scores": "6"}
{"rating": "12", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/1363.png", "name": "Минай", "games": "5", "wins": "1", "draws": "2", "losses": "2", "goals_in": "3", "goals_out": "5", "difference": "-2", "scores": "5"}
{"rating": "13", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/1207.png", "name": "Колос", "games": "5", "wins": "1", "draws": "2", "losses": "2", "goals_in": "2", "goals_out": "9", "difference": "-7", "scores": "5"}
{"rating": "14", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/73.png", "name": "Черноморец", "games": "6", "wins": "1", "draws": "1", "losses": "4", "goals_in": "7", "goals_out": "16", "difference": "-9", "scores": "4"}
{"rating": "15", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/293.png", "name": "ПФК Львов", "games": "6", "wins": "0", "draws": "2", "losses": "4", "goals_in": "4", "goals_out": "12", "difference": "-8", "scores": "2"}
{"rating": "16", "logo": "https://s.ill.in.ua/i/football/team/logo_sm/0x20/81.png", "name": "Мариуполь", "games": "6", "wins": "0", "draws": "1", "losses": "5", "goals_in": "8", "goals_out": "15", "difference": "-7", "scores": "1"}
