# Generated by Django 3.2.7 on 2021-09-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210907_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='value',
            field=models.TextField(default='LaLaLa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
