# Generated by Django 3.2.7 on 2021-09-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='category',
            field=models.CharField(choices=[('vid', 'videos'), ('aud', 'audios'), ('doc', 'documents'), ('fot', 'fotos')], max_length=25),
        ),
    ]
